channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - pip
  - pip:
    - git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.3#egg-info=stac_ipyleaflet
    - maap-algorithms-jupyter-extension==0.3.4
    #- git+https://github.com/MAAP-Project/maap-dps-jupyter-extension.git@feature/remove-need-environmentsjson#egg-info=maap-dps-jupyter-extension
    #- git+https://github.com/MAAP-Project/maap-jupyter-server-extension.git@feature/remove-api-maap-py-instantiation#egg-info=maap-jupyter-server-extension
variables:
  TITILER_STAC_ENDPOINT: 'https://staging-stac.delta-backend.com'
  TITILER_ENDPOINT: 'https://staging-raster.delta-backend.com'
  STAC_CATALOG_NAME: 'VEDA STAC'
  STAC_CATALOG_URL: 'https://staging-stac.delta-backend.com/'
  STAC_BROWSER_URL: 'http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/'
